# Terminal Bench Configuration for Fireteam
# This config controls benchmark execution parameters

terminal_bench:
  version: "0.1.1"  # Terminal Bench dataset version
  dataset: "terminal-bench-core"  # Core dataset (80 tasks)
  concurrency: 1  # Number of concurrent tasks (start with 1 for safety/cost control)

fireteam:
  version: "main"  # Git branch/tag to test (use "main" for latest, or specific tag like "v1.0.0")
  timeout_hours: 48  # Per-task timeout (Fireteam's long-horizon advantage)
  timeout_seconds: 172800  # 48 hours in seconds (auto-calculated from timeout_hours)
  completion_threshold: 95  # Fireteam completion threshold
  validation_checks: 3  # Required consecutive validations

reporting:
  compare_to_previous: true  # Compare to previous benchmark runs
  upload_to_leaderboard: false  # Manual submission for now (set true when ready)
  progress_update_interval: 300  # Update progress report every 5 minutes (seconds)
  save_full_logs: true  # Save complete logs for all tasks

# Cost management
cost_controls:
  max_concurrent_tasks: 1  # Hard limit on concurrency
  early_stop_on_errors: false  # Continue even if some tasks fail
  dry_run: false  # Set true to test without actually running benchmark
